### ISSUE TITLE
font size auto scalling for different screen sizes

### ISSUE THREAD

**Issue by melanke** [melanke/linelay#17]
something like this
```css
.fs-fluid-15 {
    font-size: calc(10px + 0.5vw);
}
```

study `em` or `rem`
